using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Game.Data.Loading
{
    /// <summary>
    /// The Data/ folder packed into one text (A7b): what a player build reads, since the app cannot open the repository
    /// folder (D-09: Data/ stays the only source of truth; the pack is generated by the build step, never edited, never
    /// committed). Format: <c>{"schemaVersion":1,"files":{"Balance/ai.json":"…", …}}</c>.
    /// </summary>
    public sealed class PackedDataSource : IDataSource
    {
        public const int SchemaVersion = 1;
        private readonly Dictionary<string, string> _files;

        public string Description { get; }

        private PackedDataSource(Dictionary<string, string> files, string description)
        {
            _files = files;
            Description = description;
        }

        public bool Exists(string relativePath) => _files.ContainsKey(relativePath);

        public string ReadAllText(string relativePath) =>
            _files.TryGetValue(relativePath, out var text) ? text : throw new FileNotFoundException("Not in the data pack: " + relativePath);

        public IEnumerable<string> Paths => _files.Keys;

        /// <summary>Packs every .json under <paramref name="dataRoot"/> (paths relative, '/' separated, sorted).</summary>
        public static string Pack(string dataRoot)
        {
            var root = Path.GetFullPath(dataRoot);
            var files = Directory.GetFiles(root, "*.json", SearchOption.AllDirectories);
            Array.Sort(files, StringComparer.Ordinal);
            var map = new JObject();
            foreach (var f in files)
            {
                var rel = f.Substring(root.Length).TrimStart(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar).Replace('\\', '/');
                map[rel] = File.ReadAllText(f, Encoding.UTF8);
            }
            var pack = new JObject { ["schemaVersion"] = SchemaVersion, ["files"] = map };
            return pack.ToString(Formatting.None);
        }

        public static PackedDataSource FromPack(string packText, string description)
        {
            if (packText == null) throw new ArgumentNullException(nameof(packText));
            var root = JObject.Parse(packText);
            if (root.Value<int?>("schemaVersion") != SchemaVersion) throw new InvalidDataException("Unsupported data pack version.");
            var files = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (var p in (JObject)root["files"]) files[p.Key] = p.Value.Value<string>();
            return new PackedDataSource(files, description);
        }
    }
}
